/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

/**
 *
 * @author lucas
 */

import jugadores.CPU;
import jugadores.Player;
import Invasion.Invasion;
import tropas.Arquero;
import tropas.Caballero;
import tropas.Mago;
import tropas.Tropa;
import Formularios.FrmDetalleBatalla;
import batalla.RegistroBatalla;
import Formularios.FrmResultado;
import Invasion.Invasion;
import batalla.RegistroBatalla;
import java.awt.event.ActionEvent;
import jugadores.Player;
import jugadores.CPU;
import java.awt.Color;
import javax.swing.BorderFactory;
import batalla.Batalla;
import ColaBatalla.Cola;
import java.util.logging.Level;
import java.util.logging.Logger;



public class FrmBatalla extends javax.swing.JFrame {

    /**
     * Creates new form FrmBatalla
     * 
     * 
     */
        private int tropasAgregadas = 0;
        private int tropasAgregadasCpu= 0;
        private boolean cerrarAutomaticamente = true;
        private String nombreJugador;
        private Invasion invasion;
        private Player jugador;
        private CPU cpu;
        
        
        
    public FrmBatalla(String nombreJugador) {
        this.nombreJugador = nombreJugador;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        cpu = new CPU();
        
        jugador = new Player(nombreJugador);
        invasion = new Invasion(jugador, cpu);
        
        lblJugador1.setText(nombreJugador);
        lblVidaJugador.setText("Vida: "+ jugador.getCastillo().getVida());
        lblVidaCPU.setText("Vida: "+ cpu.getCastillo().getVida());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCastilloJugadorimg = new javax.swing.JLabel();
        lblCPU = new javax.swing.JLabel();
        lblCastilloCPUimg1 = new javax.swing.JLabel();
        lblVidaCPU = new javax.swing.JLabel();
        lblVidaJugador = new javax.swing.JLabel();
        lblJugador1 = new javax.swing.JLabel();
        camino2Pos3 = new javax.swing.JPanel();
        camino1Pos3 = new javax.swing.JPanel();
        camino1Pos2 = new javax.swing.JPanel();
        camino1Pos1 = new javax.swing.JPanel();
        camino2Pos2 = new javax.swing.JPanel();
        TropasCPU1 = new javax.swing.JPanel();
        camino2Pos1 = new javax.swing.JPanel();
        TropasCPU2 = new javax.swing.JPanel();
        TropasJugador1 = new javax.swing.JPanel();
        TropasCPU3 = new javax.swing.JPanel();
        TropasJugador2 = new javax.swing.JPanel();
        TropasJugador3 = new javax.swing.JPanel();
        btnEmpezarBatalla = new javax.swing.JButton();
        lbltextoTropa = new javax.swing.JLabel();
        btnVolver1 = new javax.swing.JButton();
        lbltextoTropa1 = new javax.swing.JLabel();
        lblTropasAgregadas = new javax.swing.JLabel();
        lblSeleccionarTropas = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        lblSeleccionarCamino = new javax.swing.JLabel();
        cmbTiposTropas = new javax.swing.JComboBox<>();
        btnAgregarTropa = new javax.swing.JButton();
        btnSiguienteTurno1 = new javax.swing.JButton();
        lblTropasAgregadasCPU = new javax.swing.JLabel();
        lblResultadoBatalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Batalla");
        setBackground(new java.awt.Color(238, 215, 181));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(238, 215, 181));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCastilloJugadorimg.setForeground(new java.awt.Color(51, 51, 51));
        lblCastilloJugadorimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/castillo.png"))); // NOI18N
        jPanel1.add(lblCastilloJugadorimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        lblCPU.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        lblCPU.setForeground(new java.awt.Color(51, 51, 51));
        lblCPU.setText("CPU");
        jPanel1.add(lblCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 500, -1, -1));

        lblCastilloCPUimg1.setForeground(new java.awt.Color(51, 51, 51));
        lblCastilloCPUimg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/castillo.png"))); // NOI18N
        jPanel1.add(lblCastilloCPUimg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, -1, -1));

        lblVidaCPU.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        lblVidaCPU.setForeground(new java.awt.Color(51, 51, 51));
        lblVidaCPU.setText("vida: 10");
        jPanel1.add(lblVidaCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 590, -1, -1));

        lblVidaJugador.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        lblVidaJugador.setForeground(new java.awt.Color(51, 51, 51));
        lblVidaJugador.setText("vida: 10");
        jPanel1.add(lblVidaJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        lblJugador1.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        lblJugador1.setForeground(new java.awt.Color(51, 51, 51));
        lblJugador1.setText("\"\"");
        jPanel1.add(lblJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, -1, -1));

        camino2Pos3.setBackground(new java.awt.Color(255, 51, 51));
        camino2Pos3.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(camino2Pos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 90, 80));

        camino1Pos3.setBackground(new java.awt.Color(51, 204, 255));
        camino1Pos3.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(camino1Pos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 90, 80));

        camino1Pos2.setBackground(new java.awt.Color(51, 204, 255));
        camino1Pos2.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(camino1Pos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 90, 80));

        camino1Pos1.setBackground(new java.awt.Color(51, 204, 255));
        camino1Pos1.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(camino1Pos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 90, 80));

        camino2Pos2.setBackground(new java.awt.Color(255, 51, 51));
        camino2Pos2.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(camino2Pos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 90, 80));

        TropasCPU1.setBackground(new java.awt.Color(255, 51, 51));
        TropasCPU1.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(TropasCPU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 570, 90, 140));

        camino2Pos1.setBackground(new java.awt.Color(255, 51, 51));
        camino2Pos1.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(camino2Pos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 90, 80));

        TropasCPU2.setBackground(new java.awt.Color(255, 51, 51));
        TropasCPU2.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(TropasCPU2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 570, 90, 140));

        TropasJugador1.setBackground(new java.awt.Color(51, 204, 255));
        TropasJugador1.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(TropasJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, 140));

        TropasCPU3.setBackground(new java.awt.Color(255, 51, 51));
        TropasCPU3.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(TropasCPU3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, 90, 140));

        TropasJugador2.setBackground(new java.awt.Color(51, 204, 255));
        TropasJugador2.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(TropasJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 90, 140));

        TropasJugador3.setBackground(new java.awt.Color(51, 204, 255));
        TropasJugador3.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(TropasJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 90, 140));

        btnEmpezarBatalla.setBackground(new java.awt.Color(0, 153, 153));
        btnEmpezarBatalla.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnEmpezarBatalla.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpezarBatalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cargar.png"))); // NOI18N
        btnEmpezarBatalla.setText("Empezar Batalla");
        btnEmpezarBatalla.setBorder(null);
        btnEmpezarBatalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpezarBatallaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEmpezarBatalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 400, 170, 60));

        lbltextoTropa.setBackground(new java.awt.Color(51, 51, 51));
        lbltextoTropa.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lbltextoTropa.setForeground(new java.awt.Color(51, 51, 51));
        lbltextoTropa.setText("Tropas");
        jPanel1.add(lbltextoTropa, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 530, -1, -1));

        btnVolver1.setBackground(new java.awt.Color(255, 51, 51));
        btnVolver1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnVolver1.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salir.png"))); // NOI18N
        btnVolver1.setText("Volver");
        btnVolver1.setBorder(null);
        btnVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 170, 60));

        lbltextoTropa1.setBackground(new java.awt.Color(51, 51, 51));
        lbltextoTropa1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lbltextoTropa1.setForeground(new java.awt.Color(51, 51, 51));
        lbltextoTropa1.setText("Tropas");
        jPanel1.add(lbltextoTropa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        lblTropasAgregadas.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lblTropasAgregadas.setForeground(new java.awt.Color(0, 153, 153));
        lblTropasAgregadas.setText("\"\"");
        jPanel1.add(lblTropasAgregadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        lblSeleccionarTropas.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lblSeleccionarTropas.setForeground(new java.awt.Color(255, 255, 255));
        lblSeleccionarTropas.setText("Seleccione un camino");
        jPanel1.add(lblSeleccionarTropas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 220, 20));

        jComboBox2.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(102, 102, 102));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Camino 1", "Camino 2" }));
        jComboBox2.setBorder(null);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        lblSeleccionarCamino.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lblSeleccionarCamino.setForeground(new java.awt.Color(255, 255, 255));
        lblSeleccionarCamino.setText("Seleccione una Tropa");
        jPanel1.add(lblSeleccionarCamino, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 220, 20));

        cmbTiposTropas.setBackground(new java.awt.Color(255, 255, 255));
        cmbTiposTropas.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        cmbTiposTropas.setForeground(new java.awt.Color(102, 102, 102));
        cmbTiposTropas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arquero", "Caballero", "Mago" }));
        cmbTiposTropas.setBorder(null);
        cmbTiposTropas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTiposTropasActionPerformed(evt);
            }
        });
        jPanel1.add(cmbTiposTropas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        btnAgregarTropa.setBackground(new java.awt.Color(0, 153, 153));
        btnAgregarTropa.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnAgregarTropa.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarTropa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/check.png"))); // NOI18N
        btnAgregarTropa.setText("Agregar Tropas");
        btnAgregarTropa.setBorder(null);
        btnAgregarTropa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTropaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarTropa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 190, 50));

        btnSiguienteTurno1.setBackground(new java.awt.Color(0, 153, 153));
        btnSiguienteTurno1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnSiguienteTurno1.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguienteTurno1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/check.png"))); // NOI18N
        btnSiguienteTurno1.setText("Siguiente Turno");
        btnSiguienteTurno1.setBorder(null);
        jPanel1.add(btnSiguienteTurno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 170, 60));

        lblTropasAgregadasCPU.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lblTropasAgregadasCPU.setForeground(new java.awt.Color(0, 153, 153));
        lblTropasAgregadasCPU.setText("\"\"");
        jPanel1.add(lblTropasAgregadasCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        lblResultadoBatalla.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lblResultadoBatalla.setForeground(new java.awt.Color(255, 0, 255));
        lblResultadoBatalla.setText("\"\"");
        jPanel1.add(lblResultadoBatalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 640, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 730));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTiposTropasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTiposTropasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbTiposTropasActionPerformed

    private void btnAgregarTropaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTropaActionPerformed
        // TODO add your handling code here:
        
        int limite = invasion.obtenerBatallaActual().getRonda();

        
        if (tropasAgregadas >= limite) {
        lblTropasAgregadas.setText("Llegaste al limite de esta ronda");
        return;
        }


            //Toma de datos
            String tipo = (String) cmbTiposTropas.getSelectedItem();
            String caminos= (String) jComboBox2.getSelectedItem();   
            
        
            int camino = 0;
            //Escoger Camino
             if (caminos.equals("Camino 1")) {
                 camino = 1;
             } else{
                 camino =2;
                 }
             
             //Tipo y creacion de la tropa
            Tropa tropa = new Tropa();
             
            if (tipo.equals("Arquero")) {
                
                tropa = new Arquero();
                
            } else if(tipo.equals("Caballero")){
                
                tropa = new Caballero();
            
            } else if(tipo.equals("Mago")){
            
                tropa = new Mago();
            
            } else {
            
                tipo="Arquero";
                tropa = new Arquero();
            
            }
            
            invasion.asignarTropaJugador(camino, tropa);    
            tropasAgregadas++;
            lblTropasAgregadas.setText("Tropas agregadas: " + tropasAgregadas + "/" + limite);
            mostrarTropaEnCamino(
                camino == 1 ? camino1Pos1 : camino2Pos1,
                true,
                camino
            );
            actualizarContadoresDeCola();

            
           if (tropasAgregadas == limite) {
        lblTropasAgregadas.setText("Llegaste al limite de esta ronda");
        btnAgregarTropa.setEnabled(false);
    }
           
            int limitecpu =invasion.obtenerBatallaActual().getRonda();
           
           if (tropasAgregadasCpu >= limitecpu) {
        lblTropasAgregadasCPU.setText("Tropas agregadas CPU: " + tropasAgregadasCpu + "/" + limitecpu);
            
        return;
        }
           
          
             
            invasion.prepararCPU();
            actualizarPanelesDeTropas();
            mostrarTropaEnCamino(
                camino == 1 ? camino1Pos2 : camino2Pos2,
                false,
                camino
            );
            actualizarContadoresDeCola();
            
            
           tropasAgregadasCpu++;
           
           if (tropasAgregadasCpu == limitecpu) {
       lblTropasAgregadasCPU.setText("Tropas agregadas CPU: " + tropasAgregadasCpu + "/" + limitecpu);
    }
           
           
        
    }//GEN-LAST:event_btnAgregarTropaActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        if (cerrarAutomaticamente) {
            FrmPrincipal fprincipal = new FrmPrincipal();
            fprincipal.show();
        }   
    }//GEN-LAST:event_formWindowClosed

    private void btnVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver1ActionPerformed
        // TODO add your handling code here:
        
        FrmPrincipal fprincipal = new FrmPrincipal();
        fprincipal.show();
        this.dispose();
    }//GEN-LAST:event_btnVolver1ActionPerformed
    private FrmDetalleBatalla frmDetalle;
    private void btnEmpezarBatallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpezarBatallaActionPerformed
        // TODO add your handling code here:                                
    try {
        if (tropasAgregadas == 0) {
            lblTropasAgregadas.setText("Debes agregar al menos una tropa antes de iniciar la batalla.");
            return;
        }

        if (!invasion.invasionTerminada()) {
            // Ejecutar un turno completo
            invasion.ejecutarTurnoCompleto();
            actualizarPanelesDeTropas();
            actualizarContadoresDeCola();

            // Actualizar vidas
            lblVidaJugador.setText("Vida Jugador: " + jugador.getCastillo().getVida());
            lblVidaCPU.setText("Vida CPU: " + cpu.getCastillo().getVida());

            // Actualizar detalle de batalla
            if (frmDetalle == null || !frmDetalle.isDisplayable()) {
                frmDetalle = new FrmDetalleBatalla(invasion.getRegistro());
                frmDetalle.setVisible(true);
            } else {
                frmDetalle.actualizarRegistro();
            }

            // Si la invasión terminó, mostrar resultado final
            if (invasion.invasionTerminada()) {
                String resultado = invasion.estadoInvasion();
                cerrarAutomaticamente = false;
                FrmResultado pantallaFinal = new FrmResultado(resultado);
                pantallaFinal.setVisible(true);
                this.dispose();
                return;
            }

            // Si la ronda terminó, preparar nueva ronda
            Integer rondaTerminada = invasion.siguienteRondaSiTermino();
            if (rondaTerminada != null) {
                lblResultadoBatalla.setText("Ronda " + rondaTerminada + " terminada.");
                tropasAgregadas = 0;
                btnAgregarTropa.setEnabled(true);
                lblTropasAgregadas.setText("Nueva ronda: máximo: " 
                    + (invasion.obtenerBatallaActual().getRonda()));
            }

        } else {
            // Mostrar resultado final
            String resultado = invasion.estadoInvasion();
            cerrarAutomaticamente = false;
            FrmResultado pantallaFinal = new FrmResultado(resultado);
            pantallaFinal.setVisible(true);
            this.dispose();
        }
    } catch (Exception e) {
        e.printStackTrace();
    }


    }//GEN-LAST:event_btnEmpezarBatallaActionPerformed

private void mostrarTropaEnCamino(javax.swing.JPanel panel, boolean esJugador, int camino) {
    panel.removeAll();
    panel.setLayout(null);

    Batalla batalla = invasion.obtenerBatallaActual();
    String ruta = obtenerImagenSegunCola(camino, esJugador);

    if (ruta == null) {
        panel.revalidate();
        panel.repaint();
        return;
    }

    // Imagen principal
    javax.swing.JLabel lblImagen = new javax.swing.JLabel();
    lblImagen.setBounds(0, 0, panel.getWidth(), panel.getHeight());
    lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblImagen.setVerticalAlignment(javax.swing.SwingConstants.CENTER);

    javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(getClass().getResource(ruta));
    java.awt.Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(
        panel.getWidth(),
        panel.getHeight(),
        java.awt.Image.SCALE_SMOOTH
    );
    lblImagen.setIcon(new javax.swing.ImageIcon(imagenEscalada));

    lblImagen.setBorder(javax.swing.BorderFactory.createLineBorder(
        esJugador ? java.awt.Color.BLUE : java.awt.Color.RED, 2
    ));

    panel.add(lblImagen);

    // Eliminar badge anterior si existe
    for (java.awt.Component comp : panel.getComponents()) {
        if (comp instanceof javax.swing.JLabel && "badge".equals(comp.getName())) {
            panel.remove(comp);
        }
    }

    // Badge solo si hay repeticiones del mismo tipo o de dos tipos
    int repeticiones = obtenerRepeticionesDominantes(camino, esJugador);
    if (repeticiones > 1) {
        javax.swing.JLabel badge = new javax.swing.JLabel("x" + repeticiones);
        badge.setName("badge");
        badge.setForeground(java.awt.Color.WHITE);
        badge.setBackground(new java.awt.Color(0, 0, 0, 160));
        badge.setOpaque(true);
        badge.setFont(badge.getFont().deriveFont(java.awt.Font.BOLD, 12f));
        badge.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 6, 2, 6));

        int w = 32, h = 20;
        badge.setBounds(panel.getWidth() - w - 8, 8, w, h);

        panel.add(badge, 0);
    }

    panel.revalidate();
    panel.repaint();
}


private void limpiarCamino() {
    javax.swing.JPanel[] paneles = {
        camino1Pos1, camino1Pos2, camino1Pos3,
        camino2Pos1, camino2Pos2, camino2Pos3
    };

    for (javax.swing.JPanel p : paneles) {
        p.removeAll();
        p.revalidate();
        p.repaint();
    }
}
private void mostrarSoloGanador(tropas.Tropa tJugador, tropas.Tropa tCPU) {
    if (tJugador == null && tCPU == null){
        return;
    }
    
    tropas.Tropa ganador = null;
    boolean esJugador = false;
    
    if (tJugador != null && tCPU == null){
        ganador = tJugador;
        esJugador = true;
    } else if (tJugador == null && tCPU != null){
        ganador =tCPU;
        esJugador = false;
    }else if (tJugador != null && tCPU != null){
        if (tJugador.getDanio() > tCPU.getDanio()) {
            ganador = tJugador;
            esJugador = true;
        }else if (tCPU.getDanio() > tJugador.getDanio()) {
            ganador = tCPU;
            esJugador = false;
        }else {
            limpiarCamino();
            return;
          }  
    }
    
    if (ganador == null){
        return;
    }
    
    limpiarCamino();
    mostrarTropaEnCamino(camino1Pos2, esJugador, 1);
    actualizarContadoresDeCola();
    
    javax.swing.Timer timer = new javax.swing.Timer(2000, new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            limpiarCamino();
        }
    });
    timer.setRepeats(false);
    timer.start();
    
}
private void mostrarGanadorPorCamino(Tropa j, Tropa c, int camino) {
    if (j == null && c == null) {
        return;
    }

    Tropa ganador = null;
    boolean esJugador = false;

    if (j != null && c == null) {
        ganador = j;
        esJugador = true;
    } else if (j == null && c != null) {
        ganador = c;
        esJugador = false;
    } else {
        // Hay tropa de los dos lados
        if (j.getFortaleza().equals(c.getTipo())) {
            ganador = j;
            esJugador = true;
        } else if (c.getFortaleza().equals(j.getTipo())) {
            ganador = c;
            esJugador = false;
        } else {
            // empate: no se muestra nadie
            return;
        }
    }

    javax.swing.JPanel panel;

    if (camino == 1) {
        panel = esJugador ? camino1Pos1 : camino2Pos1;
    } else {
        panel = esJugador ? camino1Pos2 : camino2Pos2;
    }

    // Mostrar solo al ganador
    mostrarTropaEnCamino(panel, esJugador, camino);

    // Quitar ganador después de 2 segundos
    javax.swing.Timer t = new javax.swing.Timer(2000, new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            limpiarCamino();
        }
    });
    t.setRepeats(false);
    t.start();
}
private void actualizarPanelesDeTropas() {
    // Camino 1
    Tropa tJugador1 = invasion.obtenerBatallaActual().getTropaJugador(1);
    Tropa tCPU1 = invasion.obtenerBatallaActual().getTropaCPU(1);

    mostrarTropaEnCamino(camino1Pos1, true, 1);
    mostrarTropaEnCamino(camino1Pos2, false, 1);

    // Camino 2
    Tropa tJugador2 = invasion.obtenerBatallaActual().getTropaJugador(2);
    Tropa tCPU2 = invasion.obtenerBatallaActual().getTropaCPU(2);

    mostrarTropaEnCamino(camino2Pos1, true, 2);
    mostrarTropaEnCamino(camino2Pos2, false, 2);

}
private void setBadgeCount(javax.swing.JPanel panel, int count) {
    // Remueve badges previos con nombre "badge"
    for (java.awt.Component c : panel.getComponents()) {
        if ("badge".equals(c.getName())) {
            panel.remove(c);
        }
    }

    if (count <= 1) {
        panel.revalidate();
        panel.repaint();
        return;
    }

    javax.swing.JLabel badge = new javax.swing.JLabel("x" + count);
    badge.setName("badge");
    badge.setForeground(java.awt.Color.WHITE);
    badge.setBackground(new java.awt.Color(0, 0, 0, 160));
    badge.setOpaque(true);
    badge.setFont(badge.getFont().deriveFont(java.awt.Font.BOLD, 12f));
    badge.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 6, 2, 6));

    panel.setLayout(null);
    int w = 28, h = 18;
    badge.setBounds(panel.getWidth() - w - 6, 6, w, h);
    panel.add(badge);
    panel.revalidate();
    panel.repaint();
}
private void actualizarContadoresDeCola() {
    Batalla batalla = invasion.obtenerBatallaActual();

    // Camino 1
    setBadgeCount(camino1Pos1, batalla.getCantidadTropasJugador(1));
    setBadgeCount(camino1Pos2, batalla.getCantidadTropasCPU(1));

    // Camino 2
    setBadgeCount(camino2Pos1, batalla.getCantidadTropasJugador(2));
    setBadgeCount(camino2Pos2, batalla.getCantidadTropasCPU(2));
}
private String obtenerImagenCombinada(Tropa t1, Tropa t2) {
    if (t1 == null || t2 == null) return null;

    String tipo1 = t1.getClass().getSimpleName();
    String tipo2 = t2.getClass().getSimpleName();

    // Ordenar alfabéticamente para evitar duplicados
    String a = tipo1.compareTo(tipo2) <= 0 ? tipo1 : tipo2;
    String b = tipo1.compareTo(tipo2) <= 0 ? tipo2 : tipo1;

    if (a.equals("Arquero") && b.equals("Caballero")) return "/imagenes/arquero_caballero.png";
    if (a.equals("Caballero") && b.equals("Mago")) return "/imagenes/caballero_mago.png";
    if (a.equals("Arquero") && b.equals("Mago")) return "/imagenes/mago_arquero.png";
    if (!tipo1.equals(tipo2)) return "/imagenes/todos.png";
    return null;
}
private Tropa obtenerSegundaTropa(int camino, boolean esJugador) {
    Cola original = esJugador
        ? (camino == 1 ? invasion.obtenerBatallaActual().camino1Jugador : invasion.obtenerBatallaActual().camino2Jugador)
        : (camino == 1 ? invasion.obtenerBatallaActual().camino1CPU : invasion.obtenerBatallaActual().camino2CPU);

    if (original == null) return null;

    Cola temp = new Cola();
    Tropa segunda = null;
    int contador = 0;

    while (!original.estaVacia()) {
        try {
            Object obj = original.desencolar();
            temp.encolar((Tropa) obj); 
            contador++;
            if (contador == 2) {
                segunda = (Tropa) obj;
                break;
            }
        } catch (Exception ex) {
            Logger.getLogger(FrmBatalla.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Restaurar cola
    while (!temp.estaVacia()) {
        try {
            original.encolar(temp.desencolar());
        } catch (Exception ex) {
            Logger.getLogger(FrmBatalla.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    return segunda;
}
private String obtenerImagenSegunCola(int camino, boolean esJugador) {
    Batalla batalla = invasion.obtenerBatallaActual();
    Cola cola = esJugador ? batalla.getCaminoJugador(camino) : batalla.getCaminoCPU(camino);

    if (cola == null || cola.estaVacia()) return null;

    // Contadores por tipo
    int caballeros = 0, arqueros = 0, magos = 0;

    Cola temp = new Cola();
    while (!cola.estaVacia()) {
        try {
            Tropa t = (Tropa) cola.desencolar();
            temp.encolar(t);
            
            if (t instanceof Caballero) caballeros++;
            else if (t instanceof Arquero) arqueros++;
            else if (t instanceof Mago) magos++;
        } catch (Exception ex) {
            Logger.getLogger(FrmBatalla.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    while (!temp.estaVacia()) {
        try {
            cola.encolar(temp.desencolar());
        } catch (Exception ex) {
            Logger.getLogger(FrmBatalla.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Decidir imagen
    int tipos = (caballeros > 0 ? 1 : 0) + (arqueros > 0 ? 1 : 0) + (magos > 0 ? 1 : 0);

    if (tipos == 1) {
        if (caballeros > 0) return "/imagenes/caballero.png";
        if (arqueros > 0) return "/imagenes/arquero.png";
        if (magos > 0) return "/imagenes/mago.png";
    } else if (tipos == 2) {
        if (caballeros > 0 && arqueros > 0) return "/imagenes/arquero_caballero.png";
        if (caballeros > 0 && magos > 0) return "/imagenes/caballero_mago.png";
        if (arqueros > 0 && magos > 0) return "/imagenes/mago_arquero.png";
    } else if (tipos == 3) {
        return "/imagenes/todos.png";
    }

    return null;
}
private int obtenerRepeticionesDominantes(int camino, boolean esJugador) {
    Batalla batalla = invasion.obtenerBatallaActual();
    Cola cola = esJugador ? batalla.getCaminoJugador(camino) : batalla.getCaminoCPU(camino);

    if (cola == null || cola.estaVacia()) return 0;

    int caballeros = 0, arqueros = 0, magos = 0;

    Cola temp = new Cola();
    while (!cola.estaVacia()) {
        try {
            Tropa t = (Tropa) cola.desencolar();
            temp.encolar(t);
            
            if (t instanceof Caballero) caballeros++;
            else if (t instanceof Arquero) arqueros++;
            else if (t instanceof Mago) magos++;
        } catch (Exception ex) {
            Logger.getLogger(FrmBatalla.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    while (!temp.estaVacia()) {
        try {
            cola.encolar(temp.desencolar());
        } catch (Exception ex) {
            Logger.getLogger(FrmBatalla.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    int tipos = (caballeros > 0 ? 1 : 0) + (arqueros > 0 ? 1 : 0) + (magos > 0 ? 1 : 0);

    if (tipos == 1) {
        return Math.max(caballeros, Math.max(arqueros, magos));
    } else if (tipos == 2) {
        // Si hay dos tipos, y ambos tienen más de 1, mostrar el mínimo
        int[] repeticiones = {caballeros, arqueros, magos};
        int min = Integer.MAX_VALUE;
        for (int r : repeticiones) {
            if (r > 0) min = Math.min(min, r);
        }
        return min > 1 ? min : 0;
    }

    // Si hay 3 tipos distintos, no mostrar badge
    return 0;
}

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TropasCPU1;
    private javax.swing.JPanel TropasCPU2;
    private javax.swing.JPanel TropasCPU3;
    private javax.swing.JPanel TropasJugador1;
    private javax.swing.JPanel TropasJugador2;
    private javax.swing.JPanel TropasJugador3;
    private javax.swing.JButton btnAgregarTropa;
    private javax.swing.JButton btnEmpezarBatalla;
    private javax.swing.JButton btnSiguienteTurno1;
    private javax.swing.JButton btnVolver1;
    private javax.swing.JPanel camino1Pos1;
    private javax.swing.JPanel camino1Pos2;
    private javax.swing.JPanel camino1Pos3;
    private javax.swing.JPanel camino2Pos1;
    private javax.swing.JPanel camino2Pos2;
    private javax.swing.JPanel camino2Pos3;
    private javax.swing.JComboBox<String> cmbTiposTropas;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCPU;
    private javax.swing.JLabel lblCastilloCPUimg1;
    private javax.swing.JLabel lblCastilloJugadorimg;
    private javax.swing.JLabel lblJugador1;
    private javax.swing.JLabel lblResultadoBatalla;
    private javax.swing.JLabel lblSeleccionarCamino;
    private javax.swing.JLabel lblSeleccionarTropas;
    private javax.swing.JLabel lblTropasAgregadas;
    private javax.swing.JLabel lblTropasAgregadasCPU;
    private javax.swing.JLabel lblVidaCPU;
    private javax.swing.JLabel lblVidaJugador;
    private javax.swing.JLabel lbltextoTropa;
    private javax.swing.JLabel lbltextoTropa1;
    // End of variables declaration//GEN-END:variables
}
