/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

/**
 *
 * @author lucas
 */
import java.awt.Color;
import javax.swing.BorderFactory;
import jugadores.CPU;
import jugadores.Player;

import batalla.Batalla;
import java.util.logging.Level;
import java.util.logging.Logger;
import tropas.Arquero;
import tropas.Caballero;
import tropas.Mago;
import tropas.Tropa;
public class FrmBatalla extends javax.swing.JFrame {

    /**
     * Creates new form FrmBatalla
     * 
     * 
     */
        private int tropasAgregadas = 0;
        private int tropasAgregadasCpu= 0;

        private String nombreJugador;
        private Batalla batalla;
        private Player jugador;
        private CPU cpu;
        
        
        
    public FrmBatalla(String nombreJugador) {
        this.nombreJugador = nombreJugador;
        initComponents();
        cpu = new CPU();
        
        jugador = new Player(nombreJugador);
        batalla = new Batalla(jugador, cpu);
        
        lblJugador1.setText(nombreJugador);
        lblVidaJugador.setText("Vida: "+ jugador.getCastillo().getVida());
        lblVidaCPU.setText("Vida: "+ cpu.getCastillo().getVida());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCastilloJugadorimg = new javax.swing.JLabel();
        lblCPU = new javax.swing.JLabel();
        lblCastilloCPUimg1 = new javax.swing.JLabel();
        lblVidaCPU = new javax.swing.JLabel();
        lblVidaJugador = new javax.swing.JLabel();
        lblJugador1 = new javax.swing.JLabel();
        camino2Pos3 = new javax.swing.JPanel();
        camino1Pos3 = new javax.swing.JPanel();
        camino1Pos2 = new javax.swing.JPanel();
        camino1Pos1 = new javax.swing.JPanel();
        camino2Pos2 = new javax.swing.JPanel();
        TropasCPU1 = new javax.swing.JPanel();
        camino2Pos1 = new javax.swing.JPanel();
        TropasCPU2 = new javax.swing.JPanel();
        TropasJugador1 = new javax.swing.JPanel();
        TropasCPU3 = new javax.swing.JPanel();
        TropasJugador2 = new javax.swing.JPanel();
        TropasJugador3 = new javax.swing.JPanel();
        btnEmpezarBatalla = new javax.swing.JButton();
        lbltextoTropa = new javax.swing.JLabel();
        btnVolver1 = new javax.swing.JButton();
        lbltextoTropa1 = new javax.swing.JLabel();
        lblTropasAgregadas = new javax.swing.JLabel();
        lblSeleccionarTropas = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        lblSeleccionarCamino = new javax.swing.JLabel();
        cmbTiposTropas = new javax.swing.JComboBox<>();
        btnAgregarTropa = new javax.swing.JButton();
        btnSiguienteTurno1 = new javax.swing.JButton();
        lblTropasAgregadasCPU = new javax.swing.JLabel();
        lblResultadoBatalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Batalla");
        setBackground(new java.awt.Color(238, 215, 181));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(238, 215, 181));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCastilloJugadorimg.setForeground(new java.awt.Color(51, 51, 51));
        lblCastilloJugadorimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/castillo.png"))); // NOI18N
        jPanel1.add(lblCastilloJugadorimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        lblCPU.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        lblCPU.setForeground(new java.awt.Color(51, 51, 51));
        lblCPU.setText("CPU");
        jPanel1.add(lblCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 500, -1, -1));

        lblCastilloCPUimg1.setForeground(new java.awt.Color(51, 51, 51));
        lblCastilloCPUimg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/castillo.png"))); // NOI18N
        jPanel1.add(lblCastilloCPUimg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, -1, -1));

        lblVidaCPU.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        lblVidaCPU.setForeground(new java.awt.Color(51, 51, 51));
        lblVidaCPU.setText("vida: 10");
        jPanel1.add(lblVidaCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 590, -1, -1));

        lblVidaJugador.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        lblVidaJugador.setForeground(new java.awt.Color(51, 51, 51));
        lblVidaJugador.setText("vida: 10");
        jPanel1.add(lblVidaJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        lblJugador1.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        lblJugador1.setForeground(new java.awt.Color(51, 51, 51));
        lblJugador1.setText("\"\"");
        jPanel1.add(lblJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, -1, -1));

        camino2Pos3.setBackground(new java.awt.Color(255, 51, 51));
        camino2Pos3.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(camino2Pos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 90, 80));

        camino1Pos3.setBackground(new java.awt.Color(51, 204, 255));
        camino1Pos3.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(camino1Pos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 90, 80));

        camino1Pos2.setBackground(new java.awt.Color(51, 204, 255));
        camino1Pos2.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(camino1Pos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 90, 80));

        camino1Pos1.setBackground(new java.awt.Color(51, 204, 255));
        camino1Pos1.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(camino1Pos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 90, 80));

        camino2Pos2.setBackground(new java.awt.Color(255, 51, 51));
        camino2Pos2.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(camino2Pos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 90, 80));

        TropasCPU1.setBackground(new java.awt.Color(255, 51, 51));
        TropasCPU1.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(TropasCPU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 570, 90, 140));

        camino2Pos1.setBackground(new java.awt.Color(255, 51, 51));
        camino2Pos1.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(camino2Pos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 90, 80));

        TropasCPU2.setBackground(new java.awt.Color(255, 51, 51));
        TropasCPU2.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(TropasCPU2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 570, 90, 140));

        TropasJugador1.setBackground(new java.awt.Color(51, 204, 255));
        TropasJugador1.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(TropasJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, 140));

        TropasCPU3.setBackground(new java.awt.Color(255, 51, 51));
        TropasCPU3.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(TropasCPU3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, 90, 140));

        TropasJugador2.setBackground(new java.awt.Color(51, 204, 255));
        TropasJugador2.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(TropasJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 90, 140));

        TropasJugador3.setBackground(new java.awt.Color(51, 204, 255));
        TropasJugador3.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(TropasJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 90, 140));

        btnEmpezarBatalla.setBackground(new java.awt.Color(0, 153, 153));
        btnEmpezarBatalla.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnEmpezarBatalla.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpezarBatalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cargar.png"))); // NOI18N
        btnEmpezarBatalla.setText("Empezar Batalla");
        btnEmpezarBatalla.setBorder(null);
        btnEmpezarBatalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpezarBatallaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEmpezarBatalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 400, 170, 60));

        lbltextoTropa.setBackground(new java.awt.Color(51, 51, 51));
        lbltextoTropa.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lbltextoTropa.setForeground(new java.awt.Color(51, 51, 51));
        lbltextoTropa.setText("Tropas");
        jPanel1.add(lbltextoTropa, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 530, -1, -1));

        btnVolver1.setBackground(new java.awt.Color(255, 51, 51));
        btnVolver1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnVolver1.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salir.png"))); // NOI18N
        btnVolver1.setText("Volver");
        btnVolver1.setBorder(null);
        btnVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 170, 60));

        lbltextoTropa1.setBackground(new java.awt.Color(51, 51, 51));
        lbltextoTropa1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lbltextoTropa1.setForeground(new java.awt.Color(51, 51, 51));
        lbltextoTropa1.setText("Tropas");
        jPanel1.add(lbltextoTropa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        lblTropasAgregadas.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lblTropasAgregadas.setForeground(new java.awt.Color(0, 153, 153));
        lblTropasAgregadas.setText("\"\"");
        jPanel1.add(lblTropasAgregadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        lblSeleccionarTropas.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lblSeleccionarTropas.setForeground(new java.awt.Color(255, 255, 255));
        lblSeleccionarTropas.setText("Seleccione un camino");
        jPanel1.add(lblSeleccionarTropas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 220, 20));

        jComboBox2.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(102, 102, 102));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Camino 1", "Camino 2" }));
        jComboBox2.setBorder(null);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        lblSeleccionarCamino.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lblSeleccionarCamino.setForeground(new java.awt.Color(255, 255, 255));
        lblSeleccionarCamino.setText("Seleccione una Tropa");
        jPanel1.add(lblSeleccionarCamino, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 220, 20));

        cmbTiposTropas.setBackground(new java.awt.Color(255, 255, 255));
        cmbTiposTropas.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        cmbTiposTropas.setForeground(new java.awt.Color(102, 102, 102));
        cmbTiposTropas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arquero", "Caballero", "Mago" }));
        cmbTiposTropas.setBorder(null);
        cmbTiposTropas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTiposTropasActionPerformed(evt);
            }
        });
        jPanel1.add(cmbTiposTropas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        btnAgregarTropa.setBackground(new java.awt.Color(0, 153, 153));
        btnAgregarTropa.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnAgregarTropa.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarTropa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/check.png"))); // NOI18N
        btnAgregarTropa.setText("Agregar Tropas");
        btnAgregarTropa.setBorder(null);
        btnAgregarTropa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTropaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarTropa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 190, 50));

        btnSiguienteTurno1.setBackground(new java.awt.Color(0, 153, 153));
        btnSiguienteTurno1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnSiguienteTurno1.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguienteTurno1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/check.png"))); // NOI18N
        btnSiguienteTurno1.setText("Siguiente Turno");
        btnSiguienteTurno1.setBorder(null);
        jPanel1.add(btnSiguienteTurno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 170, 60));

        lblTropasAgregadasCPU.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lblTropasAgregadasCPU.setForeground(new java.awt.Color(0, 153, 153));
        lblTropasAgregadasCPU.setText("\"\"");
        jPanel1.add(lblTropasAgregadasCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        lblResultadoBatalla.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lblResultadoBatalla.setForeground(new java.awt.Color(255, 0, 255));
        lblResultadoBatalla.setText("\"\"");
        jPanel1.add(lblResultadoBatalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 640, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 730));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTiposTropasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTiposTropasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbTiposTropasActionPerformed

    private void btnAgregarTropaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTropaActionPerformed
        // TODO add your handling code here:
        
        int limite=batalla.getRonda()+ 1;
        int contador=0;
        
        if (tropasAgregadas >= limite) {
        lblTropasAgregadas.setText("Llegaste al limite de esta ronda");
        return;
        }

        
            //Toma de datos
            String tipo = (String) cmbTiposTropas.getSelectedItem();
            String caminos= (String) jComboBox2.getSelectedItem();   
            
        
            int camino = 0;
            //Escoger Camino
             if (caminos.equals("Camino 1")) {
                 camino = 1;
             } else{
                 camino =2;
                 }
             
             //Tipo y creacion de la tropa
            Tropa tropa = new Tropa();
             
            if (tipo.equals("Arquero")) {
                
                tropa = new Arquero();
                
            } else if(tipo.equals("Caballero")){
                
                tropa = new Caballero();
            
            } else if(tipo.equals("Mago")){
            
                tropa = new Mago();
            
            } else {
            
                tipo="Arquero";
                tropa = new Arquero();
            
            }
            
            batalla.prepararJugador(camino, tropa);
            tropasAgregadas++;
            lblTropasAgregadas.setText("Tropas agregadas: " + tropasAgregadas + "/" + limite);

            
           if (tropasAgregadas == limite) {
        lblTropasAgregadas.setText("Llegaste al limite de esta ronda");
        btnAgregarTropa.setEnabled(false);
    }
           
            int limitecpu =batalla.getRonda();
           
           if (tropasAgregadasCpu >= limitecpu) {
        lblTropasAgregadasCPU.setText("Tropas agregadas CPU: " + tropasAgregadasCpu + "/" + limitecpu);
            
        return;
        }
           
          
             
            batalla.prepararCPU();
            
           tropasAgregadasCpu++;
           
           if (tropasAgregadasCpu == limitecpu) {
       lblTropasAgregadasCPU.setText("Tropas agregadas CPU: " + tropasAgregadasCpu + "/" + limitecpu);
    }
           
           
        
    }//GEN-LAST:event_btnAgregarTropaActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        FrmPrincipal fprincipal = new FrmPrincipal();
        fprincipal.show();
        this.dispose();
        
    }//GEN-LAST:event_formWindowClosed

    private void btnVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver1ActionPerformed
        // TODO add your handling code here:
        
        FrmPrincipal fprincipal = new FrmPrincipal();
        fprincipal.show();
        this.dispose();
    }//GEN-LAST:event_btnVolver1ActionPerformed

    private void btnEmpezarBatallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpezarBatallaActionPerformed
        // TODO add your handling code here:
        
                                                       
    try {
        if (!batalla.batallaTerminada()) {
            batalla.Enfrentamiento();
            lblVidaJugador.setText("Vida Jugador: " + jugador.getCastillo().getVida());
            lblVidaCPU.setText("Vida CPU: " + cpu.getCastillo().getVida());

            if (batalla.rondaTerminada()) {//todo esta vacio
               
                lblResultadoBatalla.setText("Ronda: " + batalla.getRonda() + " terminada.");
                batalla.AumentarRonda();
                tropasAgregadas = 0;//devolver parametro reiniciado
                btnAgregarTropa.setEnabled(true);//permite boton para agregar tropa
                lblTropasAgregadas.setText("Nueva ronda: " + " , maximo: "+batalla.getRonda()+" : " + 1);
                
            }

        } else {
            lblResultadoBatalla.setText("Resultado batalla: " + batalla.resultadoBatalla());
            btnEmpezarBatalla.setEnabled(false);
        }
    } catch (Exception e) {
        
    }


        
    }//GEN-LAST:event_btnEmpezarBatallaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TropasCPU1;
    private javax.swing.JPanel TropasCPU2;
    private javax.swing.JPanel TropasCPU3;
    private javax.swing.JPanel TropasJugador1;
    private javax.swing.JPanel TropasJugador2;
    private javax.swing.JPanel TropasJugador3;
    private javax.swing.JButton btnAgregarTropa;
    private javax.swing.JButton btnEmpezarBatalla;
    private javax.swing.JButton btnSiguienteTurno1;
    private javax.swing.JButton btnVolver1;
    private javax.swing.JPanel camino1Pos1;
    private javax.swing.JPanel camino1Pos2;
    private javax.swing.JPanel camino1Pos3;
    private javax.swing.JPanel camino2Pos1;
    private javax.swing.JPanel camino2Pos2;
    private javax.swing.JPanel camino2Pos3;
    private javax.swing.JComboBox<String> cmbTiposTropas;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCPU;
    private javax.swing.JLabel lblCastilloCPUimg1;
    private javax.swing.JLabel lblCastilloJugadorimg;
    private javax.swing.JLabel lblJugador1;
    private javax.swing.JLabel lblResultadoBatalla;
    private javax.swing.JLabel lblSeleccionarCamino;
    private javax.swing.JLabel lblSeleccionarTropas;
    private javax.swing.JLabel lblTropasAgregadas;
    private javax.swing.JLabel lblTropasAgregadasCPU;
    private javax.swing.JLabel lblVidaCPU;
    private javax.swing.JLabel lblVidaJugador;
    private javax.swing.JLabel lbltextoTropa;
    private javax.swing.JLabel lbltextoTropa1;
    // End of variables declaration//GEN-END:variables
}
